language: scala
scala:
- 2.12.6
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/boot/"
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" -delete
- find $HOME/.sbt -name "*.lock" -delete
install:
- ". $HOME/.nvm/nvm.sh"
- nvm install 8.7.0
- nvm use 8.7.0
- npm install jsdom
script:
- sbt -Docs3.skipDependencyUpdates headerCheck test:headerCheck scalastyle test
- sbt -Docs3.skipDependencyUpdates edu_gemini_seqexec_web_client/fullOptJS::webpack
after_script:
- $TRAVIS_BUILD_DIR/build/weigh.sh
