language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install jsdom
before_script:
  - sudo apt-get install -y rpm
script:
  - sbt ++$TRAVIS_SCALA_VERSION test:compile test
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sbt ++$TRAVIS_SCALA_VERSION seqexec_server/universal:packageZipTarball; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sbt ++$TRAVIS_SCALA_VERSION seqexec_server_test_l64/rpm:packageBin; fi'
