language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install jsdom@9.12.0
before_script:
  - sudo apt-get install -y rpm
script:
  - sudo chmod +x /usr/local/bin/sbt
  - sbt ++$TRAVIS_SCALA_VERSION -J-Xmx3G -J-XX:-UseGCOverheadLimit test
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sbt ++$TRAVIS_SCALA_VERSION seqexec_server/universal:packageZipTarball; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sbt ++$TRAVIS_SCALA_VERSION seqexec_server_gs_test/universal:packageZipTarball; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then sbt ++$TRAVIS_SCALA_VERSION seqexec_server_gn_test/universal:packageZipTarball; fi'
